### ISSUE TITLE
Allow redundant versions of metadata in non-delta staging areas

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/hca-import-validation#15]
Modify the validation tool to allow redundant versions of metadata files (i.e. two or more files for the same entity but with different versions) in non-delta (is_delta=false) staging areas.

An error should be reported if redundant versions of metadata are found in delta staging areas.

From: https://github.com/HumanCellAtlas/dcp2/blob/main/docs/dcp2_system_design.rst#altering-data-and-metadata

> Writing an entity object and a corresponding descriptor object to a staging area with the same content as that of the highest version of that entity already in TDR while using a higher version in the name of that entity or descriptor object is referred to as a redundant version. Delta staging areas must not contain redundant versions of (meta)data.

**Comment by melainalegaspi** [comment]
@danielsotirhos to provide description.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Validation tools should warn about redundant versions in non-delta staging areas and prevent redundant versions in delta staging areas."
